learnweb/moodle-theme_wwu2019

classes/layout.php, classes/output/core_renderer.php, config.php, lang/en/theme_wwu2019.php, layout/columns.php, layout/frontpage.php, scss/post.scss, scss/pre.scss, scss/preset/default.scss, scss/wwu2019/blocks.scss, scss/wwu2019/marketingboxes.scss, scss/wwu2019/slideshow.scss, settings.php, templates/frontpage.mustache, templates/slideshow.mustache, version.php
Add Marketingboxes and Slideshow
=> Design of the frontpage

classes/output/core_renderer.php
The edit button is visible for each page which allows editing (assuming the current user has the correct priviledges).
The end of page button is shown on all pages beside the login page.
=> Added an edit button and an end of page button to the main menu

scss/pre.scss, scss/wwu2019/courselayout.scss
=> Highlight highlighted sections

classes/output/core_renderer.php
=> Sort courses for each semester alphabetically

scss/wwu2019/blocks.scss, scss/wwu2019/courselayout.scss
Fixes wrapping problems in course section- and blocks headers.
Fixes #31.
=> Fix wrapping problems in course section- and block headers

classes/output/core_renderer.php, scss/wwu2019/general.scss
=> Make "turn editing mode off"-button red

scss/wwu2019/general.scss
=> Make quiznavigation visible

scss/wwu2019/general.scss
=> Ensure proper wrapping on /course/management.php

classes/output/format_topics_renderer.php, classes/output/format_weeks_renderer.php, classes/output/wwu_format_trait.php, scss/wwu2019/courselayout.scss
=> Fix display of section summaries

classes/output/core_renderer.php, templates/menu-recursion.mustache, templates/menu.mustache
=> Make relevant submenus already extended

scss/wwu2019/general.scss, scss/wwu2019/menu.scss, templates/footer.mustache
Also: If all else fails: scroll #page-content instead of body to prevent main menu going missing on smartphones when scrolling down.
=> Make Footer wrap nicely

classes/output/core_renderer.php
=> Add matomo tracking params to slide url

classes/output/core_renderer.php, scss/wwu2019/menu.scss
=> Menu: Make coursename of hidden courses gray

scss/wwu2019/courselayout.scss
=> Courselayout: Move description next to the file

classes/output/format_topcoll_renderer.php, scss/wwu2019/courselayout.scss
Course with format_topcoll:
Course with format_topcoll in editing mode:
=> Improve format_topcoll for theme_wwu2019

classes/output/core/course_renderer.php, templates/course_search_form.mustache
=> Course search: Use course search as default and add global search link

classes/output/format_topcoll_renderer.php, pix/w_arrow_down.svg, pix/w_arrow_up.svg, scss/wwu2019/courselayout.scss
- Move section availibility info ("Hidden from students") into section header
- Fix Inplace-editing for section names
=> Fixes for topcoll format

classes/output/core_renderer.php
These changes would support using the customfield_semester field for splitting courses into semesters.
=> Support Custom field type semester

classes/output/core_renderer.php, lib.php, scss/pre.scss
move theme color constant to php
=> Add status bar color for chrome on android

scss/wwu2019/general.scss
=> Breadcrumbs: Remove border and a bit of margin

scss/wwu2019/3rd-party-fixes.scss, scss/wwu2019/menu.scss
=> Fix overlapping quiz timer

scss/wwu2019/3rd-party-fixes.scss, scss/wwu2019/menu.scss
=> Fix z-index for main menu (and quiz timer)

scss/wwu2019/general.scss, scss/wwu2019/menu.scss
=> Fix word wrap in main menu

scss/wwu2019/general.scss
=> Enforce Margin on dashboard and login page

templates/core_message/message_drawer.mustache
Unser custom template etwas an das von moodle angepasst.
=> Chat: Fix our template

scss/wwu2019/theming.scss
I currently don't have an opencast test system set up, could you test it in the testsystem before merging it?
=> Dark theme: Fix for mod_opencast

scss/wwu2019/courselayout.scss
Removed useless scrollbar as well
And added a little bit of padding to the end of sections, because of symmetry
=> Fix padding on one section page

templates/core_courseformat/local/content/section/header.mustache
As section toggle already contains title
=> Screenreader: Make section title aria-hidden

templates/core_courseformat/local/content/cm/cmname.mustache
As it only contains duplicate information
=> Screenreader: Only read activity title, not icon or activity name

scss/wwu2019/theming.scss
=> Dark theme: Fix background on questions

scss/wwu2019/theming.scss
=> Darktheme: fix hover and border in calendar block

scss/wwu2019/theming.scss
=> Darktheme: Fix link color

classes/layout.php, classes/output/core_renderer.php, scss/wwu2019/courselayout.scss, scss/wwu2019/general.scss, templates/columns.mustache, templates/full_header.mustache
(all pagelayouts except `course`)
Also:
- Slightly change tab highlighting on hover
=> Add secondary navigation to incourse and report pagelayouts

classes/layout.php
in future tool_lifecycle versions
=> This (somehow) fixes breadcrumbs

scss/wwu2019/theming.scss
=> Dark theme: Fix quiz specific feedback and drag and drop text color

classes/layout.php
By passing $PAGE->get_renderer("core") instead of $OUTPUT to layout template
=> Fix $OUTPUT->main_content() not called error

scss/wwu2019/3rd-party-fixes.scss
=> Dark theme: Adjust filter overlay in mod_assign grading view

scss/wwu2019/3rd-party-fixes.scss
=> Dark mode: Fix Ratingallocates Rating table

classes/output/core_renderer.php
Goes with local_marketing pull request !5
=> Change for local marketing

scss/wwu2019/theming.scss
=> Dark theme: Fix user name having white background in profile
